
POST http://localhost:3003/donation 
Content-Type: application/json

{
    "name": "",
    "email": "",
    "phoneNumber": "", 
    "cep": "", 
    "city": "", 
    "state": "", 
    "streetAddress": "",
    "number": "",
    "complement": "",
    "neighborhood": "",
    "deviceCount": "", 
    "devices": []
}